In [2]:
import os

In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("medical_disease_prediction_10000.csv")

In [5]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [6]:
df.isnull().sum()

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.nunique()

Age                  67
Gender                2
BMI                 238
BloodPressure        91
GlucoseLevel        211
Cholesterol         201
HeartRate            56
Smoking               2
Alcohol               2
PhysicalActivity      3
FamilyHistory         2
Disease               5
dtype: int64

In [9]:
char =df.select_dtypes(include='object')
num =df.select_dtypes(exclude='object')

In [10]:
num

      Age   BMI  BloodPressure  GlucoseLevel  Cholesterol  HeartRate
0      23  17.5            102           177          161         88
1      69  31.1            118           256          147         92
2      61  31.3            114           206          193         74
3      47  23.9            105           162          253         68
4      47  28.3            148           121          280         84
...   ...   ...            ...           ...          ...        ...
9995   49  27.1            177           183          268         59
9996   84  29.2            142           215          145         77
9997   41  22.8            177           265          133         71
9998   55  29.0            126           241          298         57
9999   59  32.2            151           162          225         93

[10000 rows x 6 columns]

In [11]:
char

      Gender Smoking Alcohol PhysicalActivity FamilyHistory       Disease
0       Male      No      No           Medium            No       Healthy
1       Male      No      No             High           Yes  Pre-Diabetes
2     Female     Yes      No           Medium            No       Healthy
3     Female      No      No              Low            No       Healthy
4       Male      No     Yes             High            No       Healthy
...      ...     ...     ...              ...           ...           ...
9995    Male      No      No             High            No  Hypertension
9996    Male      No     Yes             High           Yes  Hypertension
9997    Male      No      No           Medium           Yes  Hypertension
9998    Male      No      No           Medium           Yes  Pre-Diabetes
9999    Male      No      No             High           Yes  Pre-Diabetes

[10000 rows x 6 columns]

In [12]:
df.nunique()

Age                  67
Gender                2
BMI                 238
BloodPressure        91
GlucoseLevel        211
Cholesterol         201
HeartRate            56
Smoking               2
Alcohol               2
PhysicalActivity      3
FamilyHistory         2
Disease               5
dtype: int64

In [13]:
char["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
dict={'Male':1, 'Female':2}
char["Gender"]=char["Gender"].map(dict)

In [15]:
char

      Gender Smoking Alcohol PhysicalActivity FamilyHistory       Disease
0          1      No      No           Medium            No       Healthy
1          1      No      No             High           Yes  Pre-Diabetes
2          2     Yes      No           Medium            No       Healthy
3          2      No      No              Low            No       Healthy
4          1      No     Yes             High            No       Healthy
...      ...     ...     ...              ...           ...           ...
9995       1      No      No             High            No  Hypertension
9996       1      No     Yes             High           Yes  Hypertension
9997       1      No      No           Medium           Yes  Hypertension
9998       1      No      No           Medium           Yes  Pre-Diabetes
9999       1      No      No             High           Yes  Pre-Diabetes

[10000 rows x 6 columns]

In [16]:
char["Smoking"].unique()

array(['No', 'Yes'], dtype=object)

In [17]:
char["Smoking"]=char['Smoking'].str.strip()
dict_smok={'No':0, 'Yes':1}
char["Smoking"]=char["Smoking"].map(dict_smok)

In [18]:
char

      Gender  Smoking Alcohol PhysicalActivity FamilyHistory       Disease
0          1        0      No           Medium            No       Healthy
1          1        0      No             High           Yes  Pre-Diabetes
2          2        1      No           Medium            No       Healthy
3          2        0      No              Low            No       Healthy
4          1        0     Yes             High            No       Healthy
...      ...      ...     ...              ...           ...           ...
9995       1        0      No             High            No  Hypertension
9996       1        0     Yes             High           Yes  Hypertension
9997       1        0      No           Medium           Yes  Hypertension
9998       1        0      No           Medium           Yes  Pre-Diabetes
9999       1        0      No             High           Yes  Pre-Diabetes

[10000 rows x 6 columns]

In [19]:
char['Alcohol'].unique()

array(['No', 'Yes'], dtype=object)

In [20]:
dict_alc={'No':1, 'Yes':2}
char['Alcohol']=char['Alcohol'].map(dict_alc)

In [21]:
char

      Gender  Smoking  Alcohol PhysicalActivity FamilyHistory       Disease
0          1        0        1           Medium            No       Healthy
1          1        0        1             High           Yes  Pre-Diabetes
2          2        1        1           Medium            No       Healthy
3          2        0        1              Low            No       Healthy
4          1        0        2             High            No       Healthy
...      ...      ...      ...              ...           ...           ...
9995       1        0        1             High            No  Hypertension
9996       1        0        2             High           Yes  Hypertension
9997       1        0        1           Medium           Yes  Hypertension
9998       1        0        1           Medium           Yes  Pre-Diabetes
9999       1        0        1             High           Yes  Pre-Diabetes

[10000 rows x 6 columns]

In [22]:
char['PhysicalActivity'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [23]:
dict_un={'Medium':1, 'High':2, 'Low':3}

In [24]:
char['PhysicalActivity']=char['PhysicalActivity'].map(dict_un)

In [25]:
char

      Gender  Smoking  Alcohol  PhysicalActivity FamilyHistory       Disease
0          1        0        1                 1            No       Healthy
1          1        0        1                 2           Yes  Pre-Diabetes
2          2        1        1                 1            No       Healthy
3          2        0        1                 3            No       Healthy
4          1        0        2                 2            No       Healthy
...      ...      ...      ...               ...           ...           ...
9995       1        0        1                 2            No  Hypertension
9996       1        0        2                 2           Yes  Hypertension
9997       1        0        1                 1           Yes  Hypertension
9998       1        0        1                 1           Yes  Pre-Diabetes
9999       1        0        1                 2           Yes  Pre-Diabetes

[10000 rows x 6 columns]

In [26]:
char['FamilyHistory'].unique()

array(['No', 'Yes'], dtype=object)

In [27]:
dict={'No':0, 'Yes':1}
char['FamilyHistory']=char['FamilyHistory'].map(dict)

In [28]:
char

      Gender  Smoking  Alcohol  PhysicalActivity  FamilyHistory       Disease
0          1        0        1                 1              0       Healthy
1          1        0        1                 2              1  Pre-Diabetes
2          2        1        1                 1              0       Healthy
3          2        0        1                 3              0       Healthy
4          1        0        2                 2              0       Healthy
...      ...      ...      ...               ...            ...           ...
9995       1        0        1                 2              0  Hypertension
9996       1        0        2                 2              1  Hypertension
9997       1        0        1                 1              1  Hypertension
9998       1        0        1                 1              1  Pre-Diabetes
9999       1        0        1                 2              1  Pre-Diabetes

[10000 rows x 6 columns]

In [29]:
char['Disease'].unique()

array(['Healthy', 'Pre-Diabetes', 'Hypertension', 'Heart Disease',
       'Diabetes'], dtype=object)

In [30]:
dict_dis={'Healthy':1, 'Pre-Diabetes':2, 'Hypertension':3, 'Heart Disease':4,
       'Diabetes':5}
char['Disease']=char['Disease'].map(dict_dis)

In [31]:
char

      Gender  Smoking  Alcohol  PhysicalActivity  FamilyHistory  Disease
0          1        0        1                 1              0        1
1          1        0        1                 2              1        2
2          2        1        1                 1              0        1
3          2        0        1                 3              0        1
4          1        0        2                 2              0        1
...      ...      ...      ...               ...            ...      ...
9995       1        0        1                 2              0        3
9996       1        0        2                 2              1        3
9997       1        0        1                 1              1        3
9998       1        0        1                 1              1        2
9999       1        0        1                 2              1        2

[10000 rows x 6 columns]

In [32]:
total_df=pd.concat([char,num], axis=1)

In [33]:
total_df

,Gender,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease,Age,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate
0,1,0,1,1,0,1,23,17.5,102,177,161,88
1,1,0,1,2,1,2,69,31.1,118,256,147,92
2,2,1,1,1,0,1,61,31.3,114,206,193,74
3,2,0,1,3,0,1,47,23.9,105,162,253,68
4,1,0,2,2,0,1,47,28.3,148,121,280,84
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,0,1,2,0,3,49,27.1,177,183,268,59
9996,1,0,2,2,1,3,84,29.2,142,215,145,77
9997,1,0,1,1,1,3,41,22.8,177,265,133,71
9998,1,0,1,1,1,2,55,29.0,126,241,298,57
9999,1,0,1,2,1,2,59,32.2,151,162,225,93

In [34]:
df.isnull().sum()

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
total_df.to_csv("clean_medical.csv")

In [37]:
total_df.dtypes

Gender                int64
Smoking               int64
Alcohol               int64
PhysicalActivity      int64
FamilyHistory         int64
Disease               int64
Age                   int64
BMI                 float64
BloodPressure         int64
GlucoseLevel          int64
Cholesterol           int64
HeartRate             int64
dtype: object